nodefluxio/weber

backend/Dockerfile
backend/dev.Dockerfile

Multistage docker build and runtime stages for backend
App is not compiled, and source code is accessible on the runtime docker image
Multistage docker, source code is compiled and will not available on runtime stage

[Backend] multistage docker: binarized app on runtime

---

backend/README.md
backend/args.go
backend/database/migrate.go
backend/main.go

As in this issue #33 
We must comment or uncomment the codes to use the migrate/drop table/seeder.
There is 4 commands:
- ```go run . migrate``` to migrate without removing the data
- ```go run . migrate-fresh``` to migrate with removing the data
- ```go run . seed``` to run the seeder
- ```go run . refresh``` to migrate with removing the data and run the seeder

Handle args for migrate, migrate-fresh, seed, and refresh

---

docker-compose.yml
frontend/Dockerfile

update frontend docker

---

frontend/app/components/modules/Navbar/Navbar.module.scss
frontend/app/components/modules/Navbar/Navbar.tsx

- Links on navbar doesn't work if user is not in home page
- add Navbar functionality when user is not in homepage

add Navbar functionality besides only work in home page

---

backend/database/migrate.go
backend/models/face_payment.go

There's no model schema for the face payment solution.
- Add table model schema for face payment
- Add migrator for face payment's model
- Access the [ERD here](https://dbdiagram.io/d/614d6c6b825b5b0146113ba7)
Ada beberapa penyesuaian pada struct di golang dari ERD di atas:
- `limit_payment` jadi `minimum_payment`
- `haveTwin` jadi `have_twin`
- `isActive` jadi `is_active`
- `face_payment_transactions.updated_at` dihapus karena sepertinya tidak dibutuhkan--ga ada operasi update buat tabel ini, setiap POST buat record baru.

[Beat] Add table model schema for face payment

---

frontend/pages/solutions/ekyc.tsx

using get static props on ekyc page
using getserversideprops on ekyc page

change ekyc static props to serverside

---

frontend/app/components/modules/Feedback/Feedback.tsx
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.tsx

props onclick is used for the try again button, this I think is obvious because of the naming is not the same. Also, there are currently no props for the event when the submit button is pressed. Props This is needed when we are going to give completeness when the user has successfully provided feedback.
So to solve the above problem above, I changed the onClick props to onTryAgain. I think this is clearer and plus if we wanted other props to be run during another event then this would be ambiguous. Next, I also created afterSubmit props that will be triggered when the user successfully creates feedback. This is required to trigger completeness .
since the afterSubmit props might not be used in all instances, I made the props optional to …

change onClick to onTryAgain and add afterSubmit props

---

deployment/backend.yaml
deployment/frontend.yaml

Backend and Frontend Deployment Config
No deployment config for k8s cluster nodeflux
Deployment config for backend and frontend

add backend and frontend deployment yaml

---

frontend/app/components/templates/FacePaymentPage/FacePaymentPage.module.scss
frontend/app/components/templates/FacePaymentPage/FacePaymentPage.tsx
frontend/pages/solutions/face-payment.tsx

No face payment page.
An empty face payment page is provided for FE development, accessed via `/solutions/face-payment`

[FE] Face Payment Template Page Component

---

frontend/app/components/templates/EkycPage/EkycPage.tsx

EkycPage caused lint error because of previous refactor on Feedback component
.## What is the new behavior?
fix onClick's feedback in EkycPage

fix onClick's feedback in EkycPage

---

frontend/pages/index.tsx

We fetch services endpoint 3 times to get services
Only fetch one time to get all services in landing page

Refactor fetch services endpoint 3 times to be 1 time in landing page

---

backend/routes.go

the `/ekyc` route was accidentally deleted on the previous resolve conflict.
restore deleted `/ekyc` router/.

[Beat] Restore deleted ekyc route on previous resolve conflict

---

frontend/app/components/modules/Banner/Banner.module.scss
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.tsx

SESSION_ID_ERROR is imported from the wrong module on AnalyticsPage
SESSION_ID_ERROR is imported from the constants module on AnalyticsPage

hotfix analyticsPage

---

frontend/app/types/elements.ts
frontend/app/types/responses.ts

- Double type declarations on elementsts and responses.ts
- Undeclared field `type` on `Service`
- Delete the FaceLiveness declaration on responses.ts
- Service now has field `type`

Hotfix FE Build

---

frontend/app/components/templates/EkycPage/EkycPage.tsx

Ekyc id is hardcoded
ekyc id now dynamicly to id in database

change hardcoded to dynamic ekyc id

---

backend/middleware.go

The PATCH method is used for Face Payment Account Activation, but there is no handling for the HTTP PATCH method on the current version of CORS middleware, so it will throw an error.
Add PATCH method and delete unused methods (OPTIONS, PUT) on CORS middleware

[Beat] Add PATCH & del unused HTTP method in CORS handler

---

backend/controllers/analytic.go

One of the analytics that will be used in the Face Payment Solution demo is Face Match with Enrollment but as of the current version, the backend logic for the analytics has not been developed.
Add backend logic for face match with enrollment analytic, so it can be used on the face payment solution.

[Beat] Add requester to face match w/ enrollment 

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/pages/solutions/ekyc.tsx

There's an faulty import at one of the frontend pages
The import mentioned above has been omitted from ekyc.tsx
The frontend component can be built successfully

Fixed unresolved import on frontend

---

.github/workflows/CI.yml
frontend/.eslintrc.json
frontend/.husky/pre-commit
frontend/package-lock.json
frontend/package.json

- [x ] Code style update (formatting, renaming)
As stated in #101 
Setup githook using Husky

Setup git hook and automate lint check

---

backend/Dockerfile

When I run on Windows using docker-compose, I got this error:
Fixed it by using dos2unix to format the bash file.

Update the Dockerfile in backend to work on Windows

---

frontend/app/components/modules/ActivationForm/ActivationForm.module.scss
frontend/app/components/modules/ActivationForm/ActivationForm.tsx
frontend/app/components/modules/PaymentSetup/PaymentSetup.module.scss
frontend/app/components/modules/PaymentSetup/PaymentSetup.tsx

- There's no success display after account activation
- A success announcement is made on the popup component as follows

Add face payment activation success state

---

frontend/app/components/modules/AnalyticsResult/AnalyticsResult.module.scss
frontend/app/components/modules/AnalyticsResult/AnalyticsResult.tsx
frontend/app/components/modules/AnalyticsResultWrapper/AnalyticsResultWrapper.module.scss
frontend/app/components/templates/EkycPage/EkycPage.module.scss
frontend/app/components/templates/EkycPage/EkycPage.tsx

- AnalyticResult is not working in ekyc when generating ocr-ktp result
- Fix AnalyticResult to work with ekyc ocr-ktp
- Add className props in AnalyticResult

Fix AnalyticResult not work with ekyc ocr-ktp

---

frontend/app/components/elements/PinInput/PinInput.tsx
frontend/app/components/modules/ActivationForm/ActivationForm.tsx

- There's a disabled state (which is unnecessary) on the pin input
- No handler for pin code = '000000', rejected by backend
- Remove disabled state on the pin input
- Add handler for pin code = '000000'

Disabled pin form 

---

backend/README.md
backend/controllers/face_payment.go

the error code does not match the context of the error
Update response error code face payment

[Beat] Update response error code face payment

---

CHANGELOG.md

there's no changelog for v0.3.0 release
update changelog for v0.3.0 release

Update CHANGELOG.md release V0.3.0

---

CHANGELOG.md
frontend/app/components/elements/BigInput/BigInput.module.scss

big input component that used as  phone input in face payment solution doesn't adapt well with phone and tablet layout.
big input component that used as phone input now adapt well with phone and tablet layout.

make big input responsive

---

CHANGELOG.md
frontend/app/components/modules/Navbar/Navbar.tsx

Contact us in Navbar has no link
Add link to contact us in Navbar

Add link to contact us in Navbar

---

CHANGELOG.md
frontend/app/components/modules/PaymentSetup/PaymentSetup.tsx

cannot put 1000000 when set up limit payment
fix minimum payment for pin input accept 1000000

fix minimum payment for pin input accept 1000000

---

CHANGELOG.md
frontend/app/components/modules/ActivationForm/ActivationForm.tsx

Instructions in ActivationForm is ambigous/misleading
Update instruction in AcitvationForm to have 'PIN' word

Update ActivationForm 'pin' wording

---

frontend/app/components/templates/EkycPage/EkycPage.module.scss
frontend/app/components/templates/EkycPage/EkycPage.tsx

text alignment on ekyc's ocr ktp error message is not aligned to center
add text alignment center on ekyc's ocr ktp error message

add text align center to ekyc ocr error msg

---

CHANGELOG.md
backend/docker-entrypoint.sh

Backend docker image has no entrypoint for seed only
Add entrypoint script to execute `backend seed`

add entrypoint for command seed only

---

CHANGELOG.md
frontend/app/components/modules/PaymentForm/PaymentForm.tsx

- The phone number input field on PaymentForm did not provide enough insight for users to input numbers only (without any other symbols)
- Changed phone number input placeholder text (add example format)
- Changed error message on wrong input format

[Frontend] Quick fix on phone number input field

---

.env.example
.gitignore
CHANGELOG.md
backend/.env.example
backend/controllers/innovation.go
backend/database/seed.go

The current version of the backend to make a request to the new innovation API hits the URL defined in .env and only supports OCR receipt API URL, with variable names in .env URL_OCR_RECEIPT.
Renamed the URL_OCR_RECEIPT variable in .env to URL_INNOVATIONS and updated the mechanism in the controller code to combine the value of URL_INNOVATIONS with the slug as the base url.

[Beat] Update HTTP Requester for Innovation to Use env BASE_URL Dinamically by Slug

---

CHANGELOG.md
backend/controllers/innovation.go
backend/database/seed.go

- Di versi sebelumnya, tipe data variabel `data` sebagai penampung untuk JSON response gue pake `map[string]interfaces{}` karena response dari API anak AI yang belum ada standarnya, dinamis, beda-beda format. 
- Sebelumnya juga gue ganti slug OCR Receipt dari `ocr-receipt` ke `ocr-struct` nyesuain slug buat jadi URL endpoint VM proxy
- Setelah gue minta ke anak AI buat distandarin response API mereka, akhirnya tipe data variabel `data` bisa gue ubah jadi pake `models.ServiceRequestResultData` biar sesuai sama analitik yang udah ada.
- Balikin nama slug OCR Receipt dari `ocr-struct` ke `ocr-receipt` karena dari endpoint API nya juga diganti nyesuain slug di frontend demo.
cc @williammfu JSON result dari OCR Receipt sekarang jadi:
```json …
```

[Beat] Update HTTP Requester for Innovation lagi

---

CHANGELOG.md
frontend/pages/analytics/[analytic_name].tsx

Currently, analytics page has title name "Solutions"
Fix analytics page title to be "Analytics"

Fix title head in [analytic-name]

---

frontend/app/api/innovationsAPI.ts
frontend/app/components/elements/CodeSnippet/CodeSnippet.module.scss
frontend/app/components/elements/CodeSnippet/CodeSnippet.tsx
frontend/app/components/modules/ReceiptDisplay/ReceiptDisplay.tsx
frontend/app/types/elements.ts
frontend/app/types/responses.ts
frontend/app/utils/utils.ts

- The current API call for OCR innovation did not follow the response payload contract
- The OCR receipt results can be displayed according to the new response format

[Frontend] Display OCR receipt new response payload

---

frontend/app/api/innovationsAPI.ts
frontend/app/types/responses.ts

- OCR receipt innovations only displays json string as result
- Fix type declaration on innovations API call so the proper result display could be displayed

[Frontend] Hotfix on innovations response type

---

CHANGELOG.md
frontend/app/components/modules/ResponsiveImage/ResponsiveImage.module.scss
frontend/app/components/modules/ResponsiveImage/ResponsiveImage.tsx

right now if we want a responsive image using next/image we need to wrap it in a div. if it only one image per page this is not a problem but if we have ten or more image which we want it to be responsive the source will be cluttered with too much image inside a div.
This MR is supposed to solve the issue I have addressed above. now we have Responsive Image component which accept src and alt as usual and accept className which we can define in the parent component.

create responsive image component

---

frontend/app/components/modules/HorizontalCard/HorizontalCard.tsx

so, in the last MR i forgot to check if title exist or not. this lead to rendered heading tag without content.
now, the heading tag isn't gonna render if title props does not exist

fix horiontal card render issue

---

CHANGELOG.md
backend/database/seed.go

Backend buat inovasi car damage assessment belum support
Nambahin seed buat Car Damage Assessment doang, fungsionalitas buat request ke API tim AI udah bisa. Time consumption-nya kurleb 6s ya
Success JSON response CDA cc @rizkybaihaqy 
```json
{
"message": "Service demo request success",
"ok": true,
"service_data": {
"job": {
"result": {
"analytic_type": "CAR_DAMAGE_ASSESSMENT",
"device": "cuda",
"result": [
{
"car_damage_assessment": [
{
"damage": "Damage",
"damage_confidence": 0.9981982111930847,
"score": 2,
"severity": "Minor",
"severity_confidence": 0.9947125911712646
},
{
"damage": "Normal",
"damage_confidence": 0.9999308586120605,
"score": 0,
"severity": "None",
"severity_confidence": 0
},
{
"damage": "Damage",
"damage_confidence": …
```

[Beat] Add new innovation Car Damage Assessment

---

CHANGELOG.md
backend/.env.example
backend/controllers/activity.go
backend/controllers/analytic.go
backend/controllers/ekyc.go
backend/controllers/face_payment.go
backend/controllers/feedback.go
backend/controllers/innovation.go
backend/controllers/request.go
backend/controllers/service.go
backend/controllers/session.go
backend/controllers/visitor.go
backend/go.mod
backend/go.sum
backend/main.go
backend/models/face_payment.go
backend/models/feedback.go
backend/models/service.go
backend/models/visitor.go
backend/models/visitor_activity.go
backend/routes.go

no logging in backend to make sure it's easier to debug in production environment
Add logs using logrus

add logging system use logrus

---

CHANGELOG.md
frontend/app/components/modules/RequestDemoForm/RequestDemoForm.tsx
frontend/app/components/templates/RequestDemoPage/RequestDemoPage.module.scss

- Currently, minimum input length for field title and company name is 1 char
- Sticky navbar not on the top of page because of margin
- Make minimum input length for field title and company name to 5 char
- Fix sticky navbar in request demo form by changing margin to padding

Edit minimal input to 5 char for job title, company name in request demo form, fix sticky navbar

---

CHANGELOG.md
frontend/app/components/modules/AnalyticsResult/AnalyticsResult.module.scss
frontend/app/components/modules/AnalyticsResult/AnalyticsResult.tsx
frontend/app/components/modules/AnalyticsResult/analytics_result.json
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.module.scss
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.tsx

- [Analytics] The result display is not scrollable (thus taking a lot of height)
- [Analytics] The loading state (waiting for the result) only displays a sentence which says "Loading..."
- [Analytics] Scrollable analytic result (with a maximum height of 360px)
- [Analytics] Add `Spinner` component while in loading state

[Frontend] Scrollable analytic result + loading state

---

frontend/app/components/modules/HCardContent/HCardContent.module.scss

horizontal card component has margin set on the component level style
remove margin styling from component level and let the parent component adjust the style as needed

remove non compoent specific style from horizontal card component

---

frontend/app/components/layouts/Footer/Footer.tsx

Link buat FAQ & Press di footer masih mengarah ke halaman Nodeflux About Us
Fix the FAQ & Press link in footer

[Feat] Update FAQ and Press link in footer

---

CHANGELOG.md
backend/database/seed.go
frontend/app/components/modules/ActivationForm/ActivationForm.tsx
frontend/app/components/modules/FaceEnrollment/FaceEnrollment.module.scss
frontend/app/components/modules/FaceEnrollment/FaceEnrollment.tsx
frontend/app/components/modules/PaymentForm/PaymentForm.tsx
frontend/app/components/modules/PaymentPay/PaymentPay.module.scss
frontend/app/components/modules/PaymentPay/PaymentPay.tsx
frontend/app/components/modules/PaymentSetup/PaymentSetup.tsx
frontend/app/components/templates/FacePaymentPage/FacePaymentPage.tsx

Copywriting untuk Face Payment belum sesuai dengan wireframe terbaru dari Tim Produk
Menyesuaikan copywriting untuk Face Payment sesuai dengan wireframe terbaru dari Tim Produk

Updating Current Face Payment Copywriting to Match with Wireframe

---

frontend/app/components/modules/Banner/Banner.module.scss
frontend/app/components/modules/Banner/Banner.tsx

text description di banner di halaman setiap services masih rata kiri
text description di banner di halaman dibuat rata kanan-kiri sesuai bm nya PM

[Feat] Justifying text description in banner service page

---

frontend/app/components/templates/HomePage/HomePage.tsx

Text di homepage banner masih "lorem ipsum" 
Menyesuaikan text di homepage banner dengan yang ada di wireframe dari Tim Produk

[Feat] Update Banner Text Title & secondTitle

---

CHANGELOG.md
frontend/app/components/templates/HomePage/HomePage.module.scss

text hero section on mobile devices is too wide
text on hero section now have max-width property
before
after

fix hero section text too wide on mobile screen

---

backend/controllers/activity.go
backend/controllers/analytic.go
backend/controllers/ekyc.go
backend/controllers/face_payment.go
backend/controllers/feedback.go
backend/controllers/innovation.go
backend/controllers/request.go
backend/controllers/service.go
backend/controllers/session.go
backend/controllers/visitor.go
backend/models/face_payment.go
backend/models/feedback.go
backend/models/service.go
backend/models/visitor.go
backend/models/visitor_activity.go

No INFO logs in the backend
minimal input 2 char for job title, company and name
Add INFO logs in backend
edit some log message
Edit minimal input to 5 char for job title, company, and name

[Beat] additional logging

---

CHANGELOG.md
frontend/app/api/analyticsAPI.ts
frontend/app/components/elements/WarningDiv/WarningDiv.module.scss
frontend/app/components/elements/WarningDiv/WarningDiv.tsx
frontend/app/components/modules/AnalyticsResultWrapper/AnalyticsResultWrapper.module.scss
frontend/app/components/modules/AnalyticsResultWrapper/AnayticsResultWrapper.tsx
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.module.scss
frontend/app/components/templates/AnalyticsPage/AnalyticsPage.tsx

- The analytic services result lacked a custom error message in case there's an error
- The analytic services now have a custom error display (using `WarningDiv`) so user could tell what mistake their uploaded photo have

[Frontend] Analytic error handling display

---

CHANGELOG.md

- Changelog for Weber v0.5.0 stayed unreleased
- Updated Changelog for Weber v0.5.0

[Changelog] Update changelog v0.5.0

---

CHANGELOG.md
frontend/app/components/templates/HomePage/HomePage.module.scss
frontend/app/components/templates/HomePage/HomePage.tsx

- The solutions card component inside the homepage has different height on the dark overlay.
- Fixed height css is added on the solutions card's dark overlay so all the parts have the same height (Please note that the card did not support lengthy copywritings)
- The solutions carousel component could only display two cards at a time on tablet width

[Frontend] Renew solution card stylings

---

frontend/app/components/modules/Banner/Banner.module.scss

Text in banner does not align with navbar
fix banner text to align navbar

fix banner text to align navbar

---

CHANGELOG.md
frontend/app/components/modules/AnalyticsResult/AnalyticsResult.tsx

There is no count field in people-density analytic
AnalyticResult now will add a count field if it is a people-density analytic

Add Count field in people-density analytic

---

CHANGELOG.md
frontend/app/components/templates/FaceOcclusionAttributePage/FaceOcclusionAttributePage.module.scss
frontend/app/components/templates/FaceOcclusionAttributePage/FaceOcclusionAttributePage.tsx

- No one tells that face is occluded or not
- Add message in face occlusion to tell does the face occluded or not

Add message does the face occluded or not

---

frontend/app/components/modules/Feedback/Feedback.module.scss
frontend/app/components/modules/Feedback/Feedback.tsx

On occasion, the backend side of the app had a could take a longer time processing the user feedback. While loading, the user button is still on an enabled state and thus user could send many requests at once.
Implemented a loading state on the submit feedback button, and thus user must wait until the backend server returned a response before resubmitting the same feedback.

[Frontend] Add loading state feedback

---

README.md

There's no navigator in main README to access frontend & backend documentation directly
Add Frontend & Backend Documentation Navigator direct link in Main README

Add Frontend & Backend Documentation Navigator in Main README

---

.github/workflows/CI-docker.yml
.github/workflows/CI.yml

docker image build still manual
automate docker image build with github workflow

add push-image-frontend and push-image-backend

---

.github/workflows/CI-docker.yml

fix CI-docker with images

---

deployment/backend.yaml
deployment/frontend.yaml

update deployment backend n frontend

---

frontend/app/components/elements/Button/Button.tsx
frontend/app/components/modules/AnalyticsContainer/AnalyticsContainer.tsx

fix stepper width overflow in md screen

---

CHANGELOG.md

Update CHANGELOG v1.1.x

---

CHANGELOG.md
frontend/app/components/layouts/Footer/Footer.tsx

NIST logo looks so huge in desktop screen size
Make NIST logo looks smaller in lg breakpoits
before
after

modify width NIST logo lg breakpoints to make it smaller

---

CHANGELOG.md
frontend/app/components/modules/SolutionCard/SolutionCard.tsx
frontend/app/components/templates/HomePage/HomePage.tsx

[HOTFIX] Solution partner external link

---

CHANGELOG.md

Update Changelog v1.3.0

---

.env.example
CHANGELOG.md
backend/.env.example
backend/README.md
backend/controllers/analytic.go
backend/controllers/passive_liveness.go
backend/database/seed.go
backend/models/service.go
backend/routes.go

- Ada kebutuhan buat nambah satu solution baru Passive Face Liveness Detection, tapi belum ada.
- Ada kebutuhan buat return `job id` dari backend ke frontend, tapi sebelumnya `job id` ga direturn ke frontend.
Belum ada backend service buat handle request for Passive Face Liveness Detection, jadi dibuat:
- satu endpoint baru: `/passive-liveness`
- seed & env baru Passive Face Liveness Detection
- returning `job id` ke frontend

[Backend] Request for Passive Liveness Detection

---

backend/controllers/analytic.go
backend/controllers/passive_liveness.go
frontend/.env.example
frontend/app/api/solutionsAPI.ts
frontend/app/components/templates/PassiveLivenessPage/PassiveLivenessPage.tsx
frontend/app/constants/constant.ts
frontend/app/types/elements.ts
frontend/app/types/responses.ts

Face liveness on demo page is using [version v1 of face liveness](https://docs.identifai.id/api-documentation/asynchronous-api/face-liveness-detection)
Update face liveness endpoint to use [face-liveness-v4 ](https://docs.identifai.id/api-documentation/asynchronous-api/passive-liveness-detection-v4)

Update face liveness endpoint to version 4

---

CHANGELOG.md
frontend/app/components/templates/PassiveLivenessPage/PassiveLivenessPage.tsx

- [ x] Enhancement
- [FRONTEND] Change message if liveness score is -1

Update wording in error message based on liveness score

---

CHANGELOG.md
frontend/app/components/modules/Cam/Cam.tsx

Ticket: https://app.clickup.com/t/2hrdgkx
Demo app di page https://demo.nodeflux.io/solutions/passive-liveness masih menggunakan passive liveness version 1, secara performance liveness V1 memiliki FAR lebih besar dari face liveness V4. 
Untuk melakukan update ke V4, masih dibutuhkan improvement di penyesuaian image input dimensi, yaitu memperbesar image dimension diangka minimum 512 x 512 px, existing demo 401 x 401
Merubah dimensi ke 512 x 512

Change minScreenshotWidth and minScreenshotHeight to 512

---

CHANGELOG.md
frontend/app/components/modules/Cam/Cam.tsx

In mobile, the dimension is set to 420x420
Use 512x512 dimension for all viewport size

Use 512x512 on video constraint dimension
